### ISSUE TITLE
LNZSnapToCenterCollectionViewLayout .scrollDirection = .vertical

### ISSUE THREAD

**Issue by wwe-johndpope** [gringoireDM/LNZCollectionLayouts#1]
any chance you this LNZSnapToCenterCollectionViewLayout could support vertical alignments?

"This collection view layout is an horizontal layout that will allow pagination for items smaller than collection." I'm looking to achieve the same effect as facebook theatre mode / where you can watch tonnes of movies.

**Comment by wwe-johndpope** [comment]
digging through github came across this that may be more suitable
https://github.com/aquarchitect/MyKit/tree/6824e7ed8f7ea8a9ee943191b6a0d6f7720138fd/Sources/iOS/Frameworks/CollectionLayout/Snapping

**Comment by gringoireDM** [comment]
Cool
