### ISSUE TITLE
'final3dTransform' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by vit008** [gringoireDM/LNZCollectionLayouts#11]
When I integrated your library at my project I faced with this Error

xxx/LNZSafariTabLayout.swift:387:25: 'final3dTransform' is inaccessible due to 'private' protection level

I think, this problem cause by (private)
`private func final3dTransform(forItemOrigin attributesOrigin: CGPoint, andSize attributesSize: CGSize, enforcingAngle angle: CGFloat? = nil) -> CATransform3D`

May be it has to be fileprivate?

(because, You use function final3dTransform at extension(at the and of file))

**Comment by gringoireDM** [comment]
Hello, which swift version are you using and which Xcode version are you using?

**Comment by vit008** [comment]
swift 4.1
xcode 9.3

**Comment by gringoireDM** [comment]
The project is in swift 4.1 as well. From Swift 4 if the access level is private, the var can still be used from extensions as long as the extension lives in the same file. My best guess here is that cocoa pods is not marking the pod project swift version to be 4.1
