### ISSUE TITLE
Unable to compile in Xcode 10

### ISSUE THREAD

**Issue by keithZumper** [gringoireDM/LNZCollectionLayouts#16]
`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`

The nil coalescing operators need to be broken up into their own variables. 

https://github.com/gringoireDM/LNZCollectionLayouts/blob/1ebff88ddb3f067da738227f8b43101bd25ea5db/LNZCollectionLayouts/Layouts/LNZSnapToCenterCollectionViewLayout.swift#L148

**Comment by gringoireDM** [comment]
Hi, there is a branch currently opened with swift 4.2 and fixes for xcode10:

https://github.com/gringoireDM/LNZCollectionLayouts/tree/swift_4_2
