### ISSUE TITLE
I want your layout in objective c please help me?

### ISSUE THREAD

**Issue by maulikshahiod** [gringoireDM/LNZCollectionLayouts#22]
I have working on app that so many customization layout.I like **LNZSnapToCenterCollectionViewLayout.swift** layout. I want your layout in objective c.I am trying to convert your layout in objective c but some issues facing. so please give me layout of **LNZSnapToCenterCollectionViewLayout.swift**. 

please help me.

**Comment by gringoireDM** [comment]
Hi, I'm sorry, but this library is in swift and I have no plans in translating it in objective c

**Comment by maulikshahiod** [comment]
Can you  reference any other third party like your third party?
