### ISSUE TITLE
How to detect the centerCell in cellforrowat

### ISSUE THREAD

**Issue by yankelandroid** [gringoireDM/LNZCollectionLayouts#23]
Hi i am using the caraouselLayout and into the cellforrowat i want to detect if the indexpath is the center cell indexpath

**Comment by gringoireDM** [comment]
There is the FocusChangedDelegate: https://github.com/gringoireDM/LNZCollectionLayouts/blob/master/LNZCollectionLayouts/Layouts/LNZSnapToCenterCollectionViewLayout.swift

It's well documented you should have no problem with that
