### ISSUE TITLE
Swift 5 Support

### ISSUE THREAD

**Issue by assaulter** [gringoireDM/LNZCollectionLayouts#24]
Are there any plans to support swift5?
I am very happy if you have the plan.

thanks.

**Comment by gringoireDM** [comment]
Will do as soon as I have some time. Sorry for the delay. We also accept PRs

**Comment by assaulter** [comment]
I create PR for swift5. 
Please check this. thanks.

https://github.com/gringoireDM/LNZCollectionLayouts/pull/25

**Comment by gringoireDM** [comment]
PR Merged
