### ISSUE TITLE
How can in I detect current index in lnzcenterlayout?

### ISSUE THREAD

**Issue by maulikshah09** [gringoireDM/LNZCollectionLayouts#27]
I have an project like center layout my requriment is current index color is red and other colors are white 
How can i achive that?

**Comment by gringoireDM** [comment]
hi, you can use the delegate that will tell you when the center has changed

**Comment by maulikshah09** [comment]
Which delegate i Have to use ?? Any delegate provided this thirdparty

**Comment by gringoireDM** [comment]
https://github.com/gringoireDM/LNZCollectionLayouts/blob/2e8a8d7dda0c7f33aee6db9aadb837846a2136d8/LNZCollectionLayouts/Layouts/LNZSnapToCenterCollectionViewLayout.swift#L98
