### ISSUE TITLE
LNZInfiniteCollectionViewLayout crash

### ISSUE THREAD

**Issue by alexandra-mikh** [gringoireDM/LNZCollectionLayouts#3]
Library is crashing the app on layout update: https://www.fabric.io/s5a/ios/apps/com.saksfifthavenue.iphone/issues/599e7c19be077a4dcc8870e7?time=last-seven-days

My guess is that this problem happens when for some reason itemCount is set to 0 when prepare() is called, so that cycleSize.width is set to 0. Or itemSize.width + interitemSpacing is 0.
`let width = (itemSize.width + interitemSpacing) * CGFloat(itemCount ?? 0)`
Later on when `override internal func items(in rect: CGRect) -> [(index:IndexPath, frame: CGRect)]` is called and itemCount is greater than 0, which is checked at the start of the method, cycleSize.width remains set to 0 and crash happens `let iFirstCycle = Int(floor((rect.origin.x - cycleStart) / cycleSize.width))`.

Fix is in the following PR:
https://github.com/gringoireDM/LNZCollectionLayouts/pull/2

**Comment by gringoireDM** [comment]
Division by zero causes a crash... it's not NaN anymore.... yep, the PR fixes the issue.
